version: '3.7'
services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules 
      - ./client:/app
    ports:
      - 4200:4200

      
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    environment:
    - MONGO_INITDB_DATABASE=animal_db
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=pass

    volumes:
      - ./server:/app
    ports:
      - 5000:5000


  mongo-server:
    image: mongo:latest     
    hostname: test_mongodb  
    environment:            
      - MONGO_INITDB_DATABASE=animal_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      #Crea un nuovo bineded volume per il container di mongoDB (condividento il file init-db.js)
      # https://stackoverflow.com/questions/42912755/how-to-create-a-db-for-mongodb-container-on-start-up
      - ./mongo-server/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro    
    ports:
      - 27017:27017